export OMP_NUM_THREADS=1

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun \
    --nproc_per_node=8 --master_port=20001 ./src/ivl/train/train_sft.py \
    --model_name_or_path ./pretrained_models/Llama-2-7b-hf \
    --data_path data/merged_en_zh-split.json \
    --output_dir ./saved_models/llama-2-7b_sharegpt/ \
    --template "llama-2" \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --num_train_epochs 3 \
    --evaluation_strategy "steps" \
    --eval_steps 1500 \
    --save_strategy "epoch" \
    --save_total_limit 3 \
    --learning_rate 1e-4 \
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --metric_for_best_model "loss" \
    --load_best_model_at_end False \
    --report_to "tensorboard" \
    --logging_dir ./logs/llama-2-7b_sharegpt/ \
    --log_level "info" \
    --ddp_timeout 7200 \
    --bf16 True \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --seed 42 \